[project]
name = 'Decentralized-Medical-Credential-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.license-status]
path = 'contracts/license-status.clar'
clarity_version = 2
epoch = 2.5

[contracts.practitioner-identit]
path = 'contracts/practitioner-identit.clar'
clarity_version = 2
epoch = 2.5

[contracts.qualification-verification]
path = 'contracts/qualification-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.specialty-certification]
path = 'contracts/specialty-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
